# Generated by Django 5.1.1 on 2024-09-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('html_url', models.URLField()),
                ('avatar_url', models.URLField()),
                ('gh_id', models.PositiveIntegerField()),
                ('last_info_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('full_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('repo_name', models.CharField(max_length=40)),
                ('html_url', models.URLField()),
                ('description', models.CharField(max_length=1000)),
                ('gh_id', models.PositiveIntegerField()),
                ('last_info_update', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.owner')),
            ],
        ),
    ]
