# Generated by Django 5.1.1 on 2024-09-09 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('html_url', models.URLField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('gh_id', models.PositiveIntegerField()),
                ('last_info_update', models.DateTimeField(verbose_name='last info update')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=40)),
                ('html_url', models.URLField()),
                ('description', models.CharField(max_length=1000)),
                ('gh_id', models.PositiveIntegerField()),
                ('last_info_update', models.DateTimeField(verbose_name='last info update')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.owner')),
            ],
        ),
    ]
